name: benchmark

on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          sudo apt update
          sudo apt install libssl-dev
          sudo apt install nginx

      - name: make httpd wrk
        run: |
          ./configure
          make httpd wrk

      - name: build echo-servers
        run: |
          bash echo-servers/build.sh

      - name: benchmark echo-servers
        run: |
          bash echo-servers/benchmark.sh

      - name: webbench
        run: |
          sudo nginx -c /etc/nginx/nginx.conf
          sudo cp html/index.html /var/www/html/index.html
          bin/httpd -c etc/httpd.conf -d
          ps aux | grep nginx
          ps aux | grep httpd
          bin/wrk -c 100 -t 2 -d 10s http://127.0.0.1:80/
          bin/wrk -c 100 -t 2 -d 10s http://127.0.0.1:8080/
